# Generated by Django 5.1 on 2024-10-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_edit_any_product", "Can edit any product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
